services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: cmoon_app

    ports:
      - "8000:80"

    environment:
      APP_ENV: local
      APP_DEBUG: true

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: cmoon-laravel
      DB_USERNAME: root
      DB_PASSWORD: ""

    depends_on:
      db:
        condition: service_healthy

    networks:
      - cmoon_net

  db:
    image: mysql:8.0

    container_name: cmoon_db

    environment:
      MYSQL_DATABASE: cmoon-laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""

    ports:
      - "3307:3306"

    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot"]
      interval: 5s
      timeout: 5s
      retries: 20

    networks:
      - cmoon_net

  phpmyadmin:
    image: phpmyadmin

    container_name: cmoon_pma

    ports:
      - "8080:80"

    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ""

    depends_on:
      db:
        condition: service_healthy

    networks:
      - cmoon_net

volumes:
  db_data:

networks:
  cmoon_net: